[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "eigsep-terrain"
description = "Digital Elevation Model tools for EIGSEP"
version = "0.1.0"
license = "MIT"
authors = [{ name = "Aaron Parsons" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "opencv-python",
    "xmltodict",
    "Pillow",
    "pillow-heif",
    "pyuvdata",
    "tqdm",
    "linsolve",
    "jax",
    "healpy",
    # not on PyPI
    "healjax @ git+https://github.com/EIGSEP/healjax.git",
    "ipython>=9.13.0",
    "matplotlib>=3.10.9",
]

[project.optional-dependencies]
img = [
    "torch",
    "transformers",
    "pymc",
    "arviz",
    "pytensor",
]
numba = ["numba"]

[tool.setuptools]
script-files = ["scripts/eigsep_terrain_pymc.py"]
include-package-data = true

[tool.black]
line-length = 79

[tool.setuptools.packages.find]
where = ["src"]
